site_name: ⚡ Spark Book ⚡
site_author: 'Noah Husby'
docs_dir: docs/
repo_name: 'iitmotorsports/spark'
repo_url: 'https://github.com/iitmotorsports/spark'
copyright: Copyright &copy; 2022 IIT Motorsports
extra:
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/iitmotorsports
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/iitmotorsports
nav:
    - Home: index.md
    - Onboarding:
      - Git: onboarding/git.md
theme:
  name: 'material'
  favicon: assets/favicon.png
  features:
    - toc.integrate 
  palette: 
    primary: red
    scheme: slate
extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

