site_name: ⚡ Spark Book ⚡
site_author: 'Noah Husby'
docs_dir: docs/
repo_name: 'iitmotorsports/spark'
repo_url: 'https://github.com/iitmotorsports/spark'
copyright: Copyright &copy; 2022 IIT Motorsports
extra:
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/iitmotorsports
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/iitmotorsports
nav:
    - Home: index.md
    - Onboarding:
      - onboarding/index.md
      - Git: onboarding/git.md
      - Terminology: onboarding/terminology.md
      - Tasks: onboarding/tasks.md
    - Hardware:
      - Battery:
        - Elcon PFC-2500: hardware/battery/elcon-pfc2500.md
    - Circuits:
        - 3.3V to 5V Analog Scale: circuits/3.3_5_scale.md
        - Temperature Monitor: circuits/temp_monitor.md
    - Resources:
      - Formula Hybrid Rules: https://drive.google.com/file/d/1qqfPue71dBHfSWaDCWYXdfh6THUAw-8l/view
      - Formula Electric Rules: https://drive.google.com/file/d/1JXlojLxfPoChLREt0dhdBYNLLnxnM2-f/view
theme:
  name: 'material'
  favicon: assets/favicon.png
  features:
    - toc.integrate 
    - navigation.indexes 
  palette: 
    primary: red
    scheme: slate
extra_css:
    - stylesheets/extra.css
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 

