site_name: ⚡ Spark Book ⚡
site_author: 'Noah Husby'
docs_dir: docs/
repo_name: 'iitmotorsports/spark'
repo_url: 'https://github.com/iitmotorsports/spark'
nav:
    - Home: index.md
theme:
  name: 'material'
  features:
    - toc.integrate 
extra_css:
    - stylesheets/extra.css
